version: "3.8"

services:
  neo4j:
    image: neo4j:5
    container_name: neo4j
    ports:
      - "7474:7474"   # Web UI
      - "7687:7687"   # Bolt Protocol
    environment:
      NEO4J_AUTH: neo4j/test123456
      NEO4JLABS_PLUGINS: '["n10s"]'
      NEO4J_dbms_security_procedures_unrestricted: n10s.*
      NEO4J_dbms_security_procedures_allowlist: n10s.*
      NEO4J_dbms_memory_heap_initial__size: 512m
      NEO4J_dbms_memory_heap_max__size: 1G
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/import
      - neo4j_plugins:/plugins

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:
